#!/usr/bin/env python3
"""Battery discharge-curve calibration for Better-Rockpod.

Turns a battery_bench.txt log (from the battery_bench plugin) into a
ready-to-use battery_levels.cfg discharge table, calibrated for the
actual cell installed in the iPod.

    python3 battcal.py battery_bench.txt -o battery_levels.cfg

See specs/0006-battery-calibration-tool.md. This fixes the *gauge*
(the "stuck at 0%" / dual-boot desync problem); it does not change
battery life.
"""

import argparse
import re
import sys


class CalibrationError(Exception):
    """Raised when a log cannot produce a valid discharge curve."""


def parse_bench_log(text):
    """Parse a battery_bench.txt into a list of (seconds, mV, mA|None).

    Comment (#) and blank lines are skipped. The current column is
    optional; a field is treated as current only when it is a plain
    integer (the trailing charger/USB flags are single characters).
    """
    samples = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        fields = [f.strip() for f in line.split(",")]
        if len(fields) < 5:
            continue
        try:
            seconds = int(fields[1])
            millivolts = int(fields[4])
        except ValueError:
            continue
        current = None
        if len(fields) >= 6:
            try:
                current = int(fields[5])
            except ValueError:
                current = None
        samples.append((seconds, millivolts, current))
    return samples


def _interp(consumed_axis, voltages, target):
    """Voltage at a given consumed-charge (or elapsed-time) target,
    linearly interpolated between the nearest samples."""
    if target <= consumed_axis[0]:
        return voltages[0]
    if target >= consumed_axis[-1]:
        return voltages[-1]
    lo = 0
    while lo < len(consumed_axis) - 1 and consumed_axis[lo + 1] < target:
        lo += 1
    x0, x1 = consumed_axis[lo], consumed_axis[lo + 1]
    v0, v1 = voltages[lo], voltages[lo + 1]
    if x1 == x0:
        return v0
    return v0 + (v1 - v0) * (target - x0) / (x1 - x0)


def discharge_curve(samples, axis=None):
    """Compute the 11-point ascending discharge table (empty..full mV).

    The percentage axis comes from measured data, never the log's own
    Level column. Charge (integrated Current[mA]) is used when the whole
    log carries a current column; otherwise elapsed time. Returns
    (curve, axis_used, info)."""
    if len(samples) < 11:
        raise CalibrationError(
            "log too short: %d samples, need at least 11" % len(samples))

    seconds = [s[0] for s in samples]
    voltages = [s[1] for s in samples]
    have_current = all(s[2] is not None for s in samples)

    if axis is None:
        axis = "charge" if have_current else "time"
    if axis == "charge" and not have_current:
        raise CalibrationError("charge axis requested but log has no current")

    # cumulative consumed axis, monotonically increasing from 0
    consumed = [0.0]
    for i in range(1, len(samples)):
        dt = seconds[i] - seconds[i - 1]
        if axis == "charge":
            # trapezoidal mA-seconds; scale is irrelevant (normalised below)
            step = (samples[i][2] + samples[i - 1][2]) / 2.0 * dt
        else:
            step = dt
        consumed.append(consumed[-1] + max(step, 0.0))

    total = consumed[-1]
    if total <= 0:
        raise CalibrationError("log has no elapsed %s" % axis)

    # sample voltage at each 10% of *remaining* charge, empty(0%)..full(100%)
    curve = []
    for pct in range(0, 101, 10):
        target_consumed = (1.0 - pct / 100.0) * total
        curve.append(int(round(_interp(consumed, voltages, target_consumed))))

    for i in range(10):
        if curve[i] >= curve[i + 1]:
            raise CalibrationError(
                "non-monotonic curve at %d%%->%d%% (%d mV >= %d mV); "
                "the bench run was likely noisy or interrupted"
                % (i * 10, (i + 1) * 10, curve[i], curve[i + 1]))

    info = {
        "samples": len(samples),
        "v_min": min(voltages),
        "v_max": max(voltages),
        "duration_s": seconds[-1] - seconds[0],
    }
    return curve, axis, info


def format_cfg(curve, shutoff, disksafe):
    """Render a battery_levels.cfg block from a discharge curve."""
    values = ", ".join(str(v) for v in curve)
    return (
        "# Generated by tools/battcal from a battery_bench.txt log.\n"
        "# Rename to battery_levels.cfg in the .rockbox directory.\n"
        "# Battery voltage(millivolt) at {0%%, 10%%, ..., 100%%} discharging\n"
        "discharge: {%s}\n\n"
        "# Uncomment to also override the safety thresholds:\n"
        "#shutoff: %d\n"
        "#disksafe: %d\n" % (values, shutoff, disksafe)
    )


def parse_discharge_line(text):
    """Recover the 11 values from a discharge: {...} block."""
    m = re.search(r"discharge:\s*\{([^}]*)\}", text)
    if not m:
        raise CalibrationError("no discharge: line found")
    return [int(x) for x in m.group(1).split(",")]


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("log", help="path to battery_bench.txt")
    ap.add_argument("-o", "--output",
                    help="write battery_levels.cfg here (default: stdout)")
    ap.add_argument("--axis", choices=["time", "charge"],
                    help="force the percentage axis (default: auto)")
    args = ap.parse_args(argv)

    with open(args.log, "r") as f:
        samples = parse_bench_log(f.read())

    try:
        curve, axis, info = discharge_curve(samples, axis=args.axis)
    except CalibrationError as e:
        sys.stderr.write("error: %s\n" % e)
        return 1

    shutoff = info["v_min"] - 50
    disksafe = info["v_min"]
    cfg = format_cfg(curve, shutoff, disksafe)

    sys.stderr.write(
        "axis: %s | samples: %d | duration: %ds | "
        "measured %d-%d mV\n"
        % (axis, info["samples"], info["duration_s"],
           info["v_min"], info["v_max"]))

    if args.output:
        with open(args.output, "w") as f:
            f.write(cfg)
        sys.stderr.write("wrote %s\n" % args.output)
    else:
        sys.stdout.write(cfg)
    return 0


if __name__ == "__main__":
    sys.exit(main())
